### ISSUE TITLE
Pabbly URL endpoint returns 500

### ISSUE THREAD

**Issue by m-ke** [cre-project/cre-backend#49] opened 2019-01-12 13:24 UTC
Even when customer ID is present I get a 500:

```
Jan 12 05:40:04 cre-backend-testing app/web.1: [c8d431db-2e64-42db-ab34-fc67521315a4]    
Jan 12 05:40:04 cre-backend-testing app/web.1: [c8d431db-2e64-42db-ab34-fc67521315a4] app/controllers/api/users_controller.rb:53:in `pabbly_redirect' 
Jan 12 05:40:04 cre-backend-testing app/web.1: [c8d431db-2e64-42db-ab34-fc67521315a4] lib/middleware/consider_all_request_json_middleware.rb:10:in `call' 
Jan 12 05:40:49 cre-backend-testing app/web.1: [9cce01dc-352c-46e1-a0c9-e47f69a8f47a] Started POST "/api/user/customer_portal_url" for 185.137.175.82 at 2019-01-12 13:40:48 +0000 
Jan 12 05:40:49 cre-backend-testing app/web.1: [9cce01dc-352c-46e1-a0c9-e47f69a8f47a] Processing by Api::UsersController#pabbly_redirect as HTML 
Jan 12 05:40:49 cre-backend-testing app/web.1: [9cce01dc-352c-46e1-a0c9-e47f69a8f47a]   Parameters: {"customer_id"=>"123", "user"=>{}} 
Jan 12 05:40:49 cre-backend-testing app/web.1: [9cce01dc-352c-46e1-a0c9-e47f69a8f47a]   User Load (2.0ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", "ca46f9f5-57b2-418f-a64c-3a558e1e395d"], ["LIMIT", 1]] 
Jan 12 05:40:49 cre-backend-testing app/web.1: [9cce01dc-352c-46e1-a0c9-e47f69a8f47a] Completed 500 Internal Server Error in 399ms (ActiveRecord: 2.0ms) 
Jan 12 05:40:49 cre-backend-testing app/web.1: [9cce01dc-352c-46e1-a0c9-e47f69a8f47a]    
Jan 12 05:40:49 cre-backend-testing app/web.1: [9cce01dc-352c-46e1-a0c9-e47f69a8f47a] NoMethodError (undefined method `[]' for nil:NilClass): 
Jan 12 05:40:49 cre-backend-testing app/web.1: [9cce01dc-352c-46e1-a0c9-e47f69a8f47a]    
Jan 12 05:40:49 cre-backend-testing app/web.1: [9cce01dc-352c-46e1-a0c9-e47f69a8f47a] app/controllers/api/users_controller.rb:53:in `pabbly_redirect' 
Jan 12 05:40:49 cre-backend-testing app/web.1: [9cce01dc-352c-46e1-a0c9-e47f69a8f47a] lib/middleware/consider_all_request_json_middleware.rb:10:in `call' 
```

2) If customer ID is not present it also returns 500 
It should return 400 if customer ID is not present

```

Jan 12 05:21:53 cre-backend-testing app/web.1: [6adac38f-38d9-4fd6-8325-244a4fe8f026] Processing by Api::UsersController#pabbly_redirect as HTML 
Jan 12 05:21:53 cre-backend-testing app/web.1: [6adac38f-38d9-4fd6-8325-244a4fe8f026]   Parameters: {"user"=>{}} 
Jan 12 05:21:53 cre-backend-testing app/web.1: [6adac38f-38d9-4fd6-8325-244a4fe8f026]   User Load (3.0ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", "ca46f9f5-57b2-418f-a64c-3a558e1e395d"], ["LIMIT", 1]] 
Jan 12 05:21:53 cre-backend-testing heroku/router: at=info method=POST path="/api/user/customer_portal_url" host=cre-backend-testing.herokuapp.com request_id=6adac38f-38d9-4fd6-8325-244a4fe8f026 fwd="185.137.175.82" dyno=web.1 connect=0ms service=474ms status=500 bytes=397 protocol=https 
Jan 12 05:21:53 cre-backend-testing app/web.1: [6adac38f-38d9-4fd6-8325-244a4fe8f026] Completed 500 Internal Server Error in 462ms (ActiveRecord: 3.0ms) 
Jan 12 05:21:53 cre-backend-testing app/web.1: [6adac38f-38d9-4fd6-8325-244a4fe8f026]    
Jan 12 05:21:53 cre-backend-testing app/web.1: [6adac38f-38d9-4fd6-8325-244a4fe8f026] NoMethodError (undefined method `[]' for nil:NilClass): 
Jan 12 05:21:53 cre-backend-testing app/web.1: [6adac38f-38d9-4fd6-8325-244a4fe8f026]    
Jan 12 05:21:53 cre-backend-testing app/web.1: [6adac38f-38d9-4fd6-8325-244a4fe8f026] app/controllers/api/users_controller.rb:53:in `pabbly_redirect' 
Jan 12 05:21:53 cre-backend-testing app/web.1: [6adac38f-38d9-4fd6-8325-244a4fe8f026] lib/middleware/consider_all_request_json_middleware.rb:10:in `call' 
```

**Comment by marionschleifer** [comment] 2019-01-12 23:41
@m-ke It should now always return 200.

Regarding the no method error, it's probably again the same problem as the create user: they send something else than it says in the documentation. I now logged the params. Could you send a request again, so that I can check?

**Comment by marionschleifer** [comment] 2019-01-13 00:03
@m-ke It now returns 200 unless the customer_id is not present, in which case it returns a 400.

The reason for the no method error is probably the same as for the customer create: they send something different than they say in their documentation. I've now logged the params. Could you try again, so that I can check and change accordingly?

**Comment by m-ke** [comment] 2019-01-13 14:11
I did now.

**Comment by marionschleifer** [comment] 2019-01-15 19:45
@m-ke @Sjefkesuit Can you have a look at this, please? :)

**Comment by Sjefkesuit** [comment] 2019-01-15 19:50
Ah I know what this is I think. Let me try to fix it

**Comment by Sjefkesuit** [comment] 2019-01-15 19:51
@marionschleifer ok, this should be fixed now for any new user signing up. Let me know if that is not the case.

**Comment by marionschleifer** [comment] 2019-01-22 10:37
@Sjefkesuit Thank you. This was exactly the cause of the error. Now it's fixed 👍

**Closed** 2019-01-22 10:38 UTC
Labels: bug
